### PR TITLE
use cmake to build the project && add libcintelhex to fix build

### PR DESCRIPTION
**Pull request by sndnvaps**
Signed-off-by: sndnvaps sndnvaps@gmail.com

### CODE REVIEW

**Comment by jnaulet** [comment]
Note tried yet (i'm on vacation)

**Comment by sndnvaps** [comment]
i have test it on ubuntu 14.04 ,, nothing wrong ..

**Comment by jnaulet** [comment]
Cool

**Comment by sndnvaps** [comment]
Use cmake , is better than use autoconf ,, 
more esay .. 
just 

```
$mkdir build 
$cd build
$cmake ../
$make 
```

**Pull request merged**
